CREATE TABLE documents (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text unique not null,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
TRUNCATE TABLE documents RESTART IDENTITY;
INSERT INTO documents (title, slug, content) VALUES ('¡Hola mundo!', 'hola-mundo', E'# Hola mundo\nEste es el contenido de mi archivo markdown.');

ALTER TABLE documents ADD COLUMN category TEXT DEFAULT 'General';
ALTER TABLE documents ADD COLUMN sort_order INTEGER DEFAULT 0;