CREATE TABLE categories (
    id bigint generated by default as identity primary key,
    name text unique not null,
    slug text unique not null,
    sort_order integer not null default 0,
    created_at timestamp with time zone not null default timezone('utc'::text, now())
);


CREATE TABLE documents (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text unique not null,
    content text not null,
    category_id bigint references categories (id) on delete set null,
    sort_order integer not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone not null default timezone('utc'::text, now()),
    constraint slug_formato check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

CREATE INDEX idx_documents_orden ON documents (category_id, sort_order);

-- =========================================
-- Trigger para mantener updated_at
-- =========================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_documents_updated_at
    BEFORE UPDATE ON documents
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();